### ISSUE TITLE
How do I install this extension?

### ISSUE THREAD

**Issue by t0stiman** [maciex/play-to-kodi#13]
Latest Firefox version, Windows 8.1

**Comment by maciex** [comment]
Use XPI file from the latest release: https://github.com/maciex/play-to-kodi/releases

**Comment by maciex** [comment]
The Add-on is already submitted to addons.mozilla.org.
Add-on is waiting for review. After that it will be listed (searchable) on addons.mozilla.org, right now it's visible via direct link.

You can view/install it from:
https://addons.mozilla.org/en-US/firefox/addon/play-to-kodi4/
