### ISSUE TITLE
[feature request] Button to open browser interface

### ISSUE THREAD

**Issue by rubdos** [maciex/play-to-kodi#15]
It would be nice if there was a button that opens a tab to `[host]:[port]`!

**Comment by maciex** [comment]
I don't understand that usage scenario. Could you elaborate, please.

**Comment by rubdos** [comment]
> I don't understand that usage scenario. Could you elaborate, please.

Sure. I'm not yet sure whether it's completely useful, but here goes!

I'm basically asking for a button in the current play-to-kodi menu, which when clicked opens the currently selected Kodi host's web interface. Play-to-kodi doesn't provide in everything that the web ui does (and it shouldn't, of course), so it would be a handy shortcut to open the interface to the selected Kodi's web interface.

EDIT: I accidentially hit "close and comment"...

**Comment by maciex** [comment]
This repository is just a fork of [play-to-xbmc-chrome](https://github.com/khloke/play-to-xbmc-chrome).

Main focus of this repository is to provide fixes making Firefox port 100% usable. Other bugs also will be fixed here, but I rather don't plan to implement new features.

You could submit this to the original author.
