### ISSUE TITLE
Add 2 more resolvers to your list

### ISSUE THREAD

**Issue by Sanjjay** [maciex/play-to-kodi#16]
Please could you the resolvers below to your list for kodi, to be able to play streams from file sharing websites.

https://github.com/Colossal1/repository.colossus.common/tree/master/script.module.urlresolver

https://github.com/Colossal1/repository.colossus.common/tree/master/script.module.liveresolver

Hope to here from you!

Sanjay

**Comment by maciex** [comment]
@Sanjjay: Please report feature requests to [main author's GitHub repository](https://github.com/khloke/play-to-xbmc-chrome).
I'm only doing a Firefox port here and would like to handle only bugs related to this.
