### ISSUE TITLE
Webinterface ports

### ISSUE THREAD

**Issue by Morgyn** [maciex/play-to-kodi#33]
Hi,

My kodi is configured to use a different port for 80 for it's web interface. Is it possible to add an option (maybe just a colon in the ip spec x.x.x.x:xx) to use alternative ports?

Thanks

**Comment by maciex** [comment]
I'm not sure where's the problem. When defining a host in Play to kodi
addon you have a separate field for the Port.
Please describe your scenario with more details, or attach screenshots.

**Comment by Morgyn** [comment]
Well this is embarrassing, this was meant for a different extension.

My apologies.
