### ISSUE TITLE
Add-on signing

### ISSUE THREAD

**Issue by TheOddler** [maciex/play-to-kodi#6]
When trying to install this from the releases I get an error stating that the addon isn't signed. There seem to be new rules in the latest version of firefox that require all addons to be signed: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by maciex** [comment]
Yes, the addon is unsigned as it's alpha release.
As of now I don't want to spend time searching how to sign the add-on, I'm providing it as unsigned.

**Comment by TheOddler** [comment]
Fair enough.

For others interested, check here for how to disable that requirement in firefox: http://winaero.com/blog/enable-unsigned-add-ons-disabled-by-firefox-43/

Also, tested it on Firefox 46 and seems to work fine.

**Comment by maciex** [comment]
Looks like the singing issue is back again:

> Firefox 48: (Pushed from Firefox 46). Release and Beta versions of Firefox for Desktop will not allow unsigned extensions to be installed, with no override. Firefox for Android will enforce add-on signing, and will retain a preference — which will be removed in a future release — to allow the user to disable signing enforcement.  [1]

I'm reopening this issue and will soon work on signing the release package.

[1] https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by maciex** [comment]
I created new Pre-release of the add-on. It's now signed so should work in latest Firefox without any problems.
It's currently not visible on [AMO](https://addons.mozilla.org). I'll contact the author one more time and ask if it's ok to publish it there.
